[phases.build]
cmds = [
  "pip install --no-cache-dir -r requirements.txt",
  "pip uninstall -y opencv-python opencv-contrib-python || true",
  "pip install --no-cache-dir --force-reinstall opencv-python-headless"
]
